CREATE DATABASE IF NOT EXISTS XYZ;

USE XYZ;

CREATE TABLE emp(
empID INT,
Name VARCHAR(50),
Salary INT
);

INSERT INTO emp VALUES(1,"adam", 25000);
INSERT INTO emp VALUES(2, "bob", 30000);
INSERT INTO emp VALUES(3, "casey", 40000);

SELECT * FROM emp;